// GENERATED by scripts/generate-last-updated.mjs — do not edit by hand.
// Regenerated on every build; see the script for how each date is derived.

export const LAST_UPDATED: Record<string, string> = {
  "/": "2026-01-18",
  "/fleet": "2026-08-26",
  "/contact": "2026-08-26",
  "/about": "2026-08-26",
  "/events": "2026-08-26",
  "/locations": "2026-08-26",
  "/locations/north-hills": "2026-08-26",
  "/locations/south-hills": "2026-08-26",
  "/locations/downtown": "2026-08-26",
  "/locations/south-side": "2026-08-26",
  "/locations/oakland": "2026-08-26",
  "/pricing": "2026-08-26",
  "/faqs": "2026-08-26",
  "/blog": "2026-05-19",
  "/blog/party-bus-pricing-guide": "2026-08-26",
  "/blog/top-events-pittsburgh": "2026-08-26",
  "/blog/party-bus-vs-limo": "2026-08-26",
  "/blog/bachelor-bachelorette-ideas": "2026-08-26",
  "/blog/wedding-transportation": "2026-08-26",
  "/blog/corporate-event-transportation": "2026-08-26",
  "/blog/concert-party-bus": "2026-08-26",
  "/blog/prom-transportation-safety": "2026-08-26",
  "/blog/party-bus-safety-tips": "2026-08-26",
  "/blog/accurate-party-bus-estimate": "2026-08-26",
  "/blog/party-buses-near-me": "2026-08-26",
  "/testimonials": "2026-08-26",
  "/privacy": "2026-08-26",
  "/terms": "2026-08-26"
};

/** Build date, used when a route is missing from the map above. */
export const BUILD_DATE = "2026-08-26";
